name: build

on:
  push:
    paths:
    - '**.cs'
    - '**.csproj'
    - '.github/workflows/build.yml'
    
  pull_request:
  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Download NiTiS Build Tools
        run: |
          cd ..
          git clone "https://github.com/NiTiS-Dev/NiTiS-Dev.github.io.git" "NiTiS-Site"
          cd NiTiS-Site
          export NBT_HOME=$(pwd)
          echo $NBT_HOME
          set
          
